name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Clone or update repo
            if [ -d "Django-API" ]; then
              cd Django-API && git pull
            else
              git clone https://github.com/${{ github.repository }} Django-API && cd Django-API
            fi

            cd ~/Django-API/myapi_server
            # Stop any running container
            docker stop djangoapp || true
            docker rm djangoapp || true

            # Build and run
            docker build -t djangoapp .
            docker run -d -p 8000:8000 --name djangoapp djangoapp
          EOF
